### ISSUE TITLE
set-cookie with suborigin header should set cookie in new cookie jar

### ISSUE THREAD

**Issue by devd** [w3c/webappsec-suborigins#27]
if you get a response with a suborigin header and a set-cookie header, the cookie should be set on the suborigin not on the parent suborigin.

**Comment by metromoxie** [comment]
I'd love a clarification about why this is needs. This adds a huge amount of implementer complexity (and probably spec complexity to modifying the cookie spec), and since the default behavior of the Suborigin is to disable access to document.cookie, that has the effect of disabling the untrusted (differently trusted?) code from accessing the cookies. So the only entity accessing the cookies is *the server*. 

That's different from the physical origin accessing cookies, and as we've previously said, the server is the authoritative source, so it seems consistent to allow it to set cookies across the board. Heck, we can provide a recommended method for separating cookies that should be tied to specific Suborigins.

**Comment by metromoxie** [comment]
I'm pretty sure we decided that this is _not_ the approach we're taking. In particular, as written up in https://w3c.github.io/webappsec-suborigins/#cookies, the `Set-Cookie` header sets cookies in the cookie jar across the physical origin, but we make suborigin documents cookie averse so that document.cookie cannot be used.

@devd, can you confirm that you agree, and if so, feel free to close this issue?

**Comment by metromoxie** [comment]
@devd I'm closing. Re-open if you feel otherwise.
